<?php

return [
    'groups' => [
        'dhl' => [
            'label' => 'DHL Integration',
            'description' => 'Komplette DHL-API-Konfiguration: Auth, Tracking, Push-Webhooks und Backend.',
            'submit_label' => 'DHL-Einstellungen speichern',
            'fields' => [
                [
                    'key' => 'dhl_auth_base_url',
                    'label' => 'Auth Service Base URL',
                    'type' => 'text',
                    'value_type' => 'string',
                    'default' => 'https://api-sandbox.dhl.com',
                    'help' => 'Basis-URL für den DHL Auth Service (Token-Ausgabe).',
                ],
                [
                    'key' => 'dhl_auth_username',
                    'label' => 'Client ID',
                    'type' => 'text',
                    'value_type' => 'string',
                    'help' => 'Client ID für die DHL-Authentifizierung.',
                ],
                [
                    'key' => 'dhl_auth_password',
                    'label' => 'Client Secret',
                    'type' => 'password',
                    'value_type' => 'secret',
                    'skip_if_empty' => true,
                    'placeholder' => 'Nur ausfüllen, um zu ändern',
                    'help' => 'Client Secret für die DHL-Authentifizierung. Leer lassen, um den aktuellen Wert zu behalten.',
                ],
                [
                    'key' => 'dhl_auth_path',
                    'label' => 'Token Pfad',
                    'type' => 'text',
                    'value_type' => 'string',
                    'default' => '/auth/v1/token',
                    'help' => 'API-Pfad für die Token-Ausgabe.',
                ],
                [
                    'key' => 'dhl_auth_token_cache_ttl',
                    'label' => 'Token Cache TTL (Sek.)',
                    'type' => 'number',
                    'value_type' => 'int',
                    'default' => 0,
                    'help' => 'Gültigkeitsdauer für gecachte Tokens in Sekunden. 0 = kein Cache.',
                ],
                [
                    'key' => 'dhl_base_url',
                    'label' => 'Tracking API Base URL',
                    'type' => 'text',
                    'value_type' => 'string',
                    'default' => 'https://api-test.dhl.com/tracking',
                    'help' => 'Basis-URL für die DHL Tracking API.',
                ],
                [
                    'key' => 'dhl_api_key',
                    'label' => 'Tracking API Key',
                    'type' => 'text',
                    'value_type' => 'string',
                    'help' => 'API Key für die DHL Tracking API.',
                ],
                [
                    'key' => 'dhl_timeout',
                    'label' => 'Tracking Timeout (Sek.)',
                    'type' => 'number',
                    'value_type' => 'int',
                    'default' => 10,
                    'help' => 'Timeout für Tracking-API-Anfragen in Sekunden.',
                ],
                [
                    'key' => 'dhl_connect_timeout',
                    'label' => 'Tracking Connect Timeout (Sek.)',
                    'type' => 'number',
                    'value_type' => 'int',
                    'default' => 5,
                    'help' => 'Timeout für Verbindungsaufbau zur Tracking-API in Sekunden.',
                ],
                [
                    'key' => 'dhl_verify_ssl',
                    'label' => 'SSL-Zertifikate prüfen (Tracking)',
                    'type' => 'checkbox',
                    'value_type' => 'bool',
                    'default' => true,
                    'checkbox_label' => 'SSL-Zertifikate für Tracking-API prüfen',
                ],
                [
                    'key' => 'dhl_push_base_url',
                    'label' => 'Push Webhooks Base URL',
                    'type' => 'text',
                    'value_type' => 'string',
                    'default' => 'https://api-test.dhl.com/tracking/push/v1',
                    'help' => 'Basis-URL für DHL Push-Webhooks.',
                ],
                [
                    'key' => 'dhl_push_api_key',
                    'label' => 'Push API Key',
                    'type' => 'text',
                    'value_type' => 'string',
                    'help' => 'API Key für DHL Push-Webhooks.',
                ],
                [
                    'key' => 'dhl_push_api_key_header',
                    'label' => 'Push API Key Header-Name',
                    'type' => 'text',
                    'value_type' => 'string',
                    'default' => 'DHL-API-Key',
                    'help' => 'HTTP-Header-Name für den Push API Key.',
                ],
                [
                    'key' => 'tracking_api_key',
                    'label' => 'Tracking Backend API Key',
                    'type' => 'text',
                    'value_type' => 'string',
                    'help' => 'API Key für das interne Tracking-Backend.',
                ],
                [
                    'key' => 'tracking_api_secret',
                    'label' => 'Tracking Backend API Secret',
                    'type' => 'password',
                    'value_type' => 'secret',
                    'skip_if_empty' => true,
                    'placeholder' => 'Nur ausfüllen, um zu ändern',
                    'help' => 'API Secret für das interne Tracking-Backend. Leer lassen, um den aktuellen Wert zu behalten.',
                ],
                [
                    'key' => 'tracking_default_service',
                    'label' => 'Standard-Service',
                    'type' => 'select',
                    'value_type' => 'string',
                    'options' => [
                        'freight' => 'DHL Freight',
                        'parcel' => 'DHL Parcel',
                    ],
                    'default' => 'freight',
                    'help' => 'Standard-Service für Tracking-Anfragen.',
                ],
                [
                    'key' => 'tracking_origin_cc',
                    'label' => 'Origin-Land (ISO)',
                    'type' => 'text',
                    'value_type' => 'string',
                    'placeholder' => 'DE',
                    'help' => 'ISO-Ländercode für den Ursprung.',
                ],
                [
                    'key' => 'tracking_requester_cc',
                    'label' => 'Requester-Land (ISO)',
                    'type' => 'text',
                    'value_type' => 'string',
                    'placeholder' => 'DE',
                    'help' => 'ISO-Ländercode für den Anfragenden.',
                ],
            ],
        ],
        'mail' => [
            'label' => 'E-Mail',
            'description' => 'Absender- und SMTP-Konfiguration für Benachrichtigungen.',
            'submit_label' => 'Mail-Einstellungen speichern',
            'fields' => [
                [
                    'key' => 'mail_from_email',
                    'label' => 'Absender E-Mail',
                    'type' => 'email',
                    'value_type' => 'string',
                    'placeholder' => 'logistics@example.com',
                ],
                [
                    'key' => 'mail_from_name',
                    'label' => 'Absender Name',
                    'type' => 'text',
                    'value_type' => 'string',
                    'placeholder' => 'AX4 Tracking',
                ],
                [
                    'key' => 'mail_transport',
                    'label' => 'Versandart',
                    'type' => 'select',
                    'value_type' => 'string',
                    'options' => [
                        'smtp' => 'SMTP-Server',
                        'log' => 'Log-Datei',
                        'mail' => 'PHP mail()',
                    ],
                    'default' => env('MAIL_MAILER', 'log'),
                ],
                [
                    'key' => 'mail_smtp_host',
                    'label' => 'SMTP Host',
                    'type' => 'text',
                    'value_type' => 'string',
                    'placeholder' => 'smtp.example.com',
                ],
                [
                    'key' => 'mail_smtp_port',
                    'label' => 'SMTP Port',
                    'type' => 'number',
                    'value_type' => 'int',
                    'placeholder' => '587',
                ],
                [
                    'key' => 'mail_smtp_encryption',
                    'label' => 'Verschlüsselung',
                    'type' => 'select',
                    'value_type' => 'string',
                    'options' => [
                        'starttls' => 'STARTTLS',
                        'ssl' => 'SSL/TLS',
                        'none' => 'Keine',
                    ],
                    'default' => 'starttls',
                ],
                [
                    'key' => 'mail_smtp_username',
                    'label' => 'SMTP Benutzer',
                    'type' => 'text',
                    'value_type' => 'string',
                    'placeholder' => 'login@example.com',
                ],
                [
                    'key' => 'mail_smtp_password',
                    'label' => 'SMTP Passwort',
                    'type' => 'password',
                    'value_type' => 'secret',
                    'skip_if_empty' => true,
                    'placeholder' => 'Nur ausfüllen, um zu ändern',
                ],
                [
                    'key' => 'mail_smtp_timeout',
                    'label' => 'Timeout (Sek.)',
                    'type' => 'number',
                    'value_type' => 'int',
                    'placeholder' => '15',
                    'default' => 15,
                ],
                [
                    'key' => 'mail_smtp_verify_peer',
                    'label' => 'TLS-Zertifikate prüfen',
                    'type' => 'checkbox',
                    'value_type' => 'bool',
                    'default' => true,
                ],
            ],
        ],
        'notifications' => [
            'label' => 'Benachrichtigungen',
            'description' => 'Konfiguration für Benachrichtigungskanäle (E-Mail, Slack, SMS).',
            'submit_label' => 'Benachrichtigungs-Einstellungen speichern',
            'fields' => [
                [
                    'key' => 'notifications.mail.enabled',
                    'label' => 'E-Mail-Kanal aktivieren',
                    'type' => 'checkbox',
                    'value_type' => 'bool',
                    'default' => true,
                    'checkbox_label' => 'E-Mail-Benachrichtigungen aktivieren',
                ],
                [
                    'key' => 'notifications.slack.enabled',
                    'label' => 'Slack-Kanal aktivieren',
                    'type' => 'checkbox',
                    'value_type' => 'bool',
                    'default' => false,
                    'checkbox_label' => 'Slack-Benachrichtigungen aktivieren',
                ],
                [
                    'key' => 'notifications.slack.webhook_url',
                    'label' => 'Slack Webhook URL',
                    'type' => 'password',
                    'value_type' => 'secret',
                    'skip_if_empty' => true,
                    'placeholder' => 'https://hooks.slack.com/services/...',
                    'help' => 'Webhook-URL für Slack-Benachrichtigungen. Leer lassen, um den aktuellen Wert zu behalten.',
                ],
                [
                    'key' => 'notifications.slack.channel',
                    'label' => 'Slack Standard-Channel',
                    'type' => 'text',
                    'value_type' => 'string',
                    'placeholder' => '#alerts',
                    'help' => 'Standard-Channel für Slack-Benachrichtigungen.',
                ],
                [
                    'key' => 'notifications.sms.enabled',
                    'label' => 'SMS-Kanal aktivieren',
                    'type' => 'checkbox',
                    'value_type' => 'bool',
                    'default' => false,
                    'checkbox_label' => 'SMS-Benachrichtigungen aktivieren',
                ],
                [
                    'key' => 'notifications.sms.sender',
                    'label' => 'SMS Absender-Kennung',
                    'type' => 'text',
                    'value_type' => 'string',
                    'placeholder' => 'Logistics',
                    'help' => 'Absender-Kennung für SMS-Benachrichtigungen.',
                ],
            ],
        ],
    ],
];
